#!/bin/bash
dotfilesDir=$(pwd)

function linkDotfile {
  dest="${HOME}/${1}"
  dateStr=$(date +%Y-%m-%d-%H%M)

  if [ -h ~/${1} ]; then
    # Existing symlink 
    echo "Removing existing symlink: ${dest}"
    rm ${dest} 

  elif [ -f "${dest}" ]; then
    # Existing file
    echo "Backing up existing file: ${dest}"
    mv ${dest}{,.${dateStr}}

  elif [ -d "${dest}" ]; then
    # Existing dir
    echo "Backing up existing dir: ${dest}"
    mv ${dest}{,.${dateStr}}
  fi

  echo "Creating new symlink: ${dest}"
  ln -s ${dotfilesDir}/${1} ${dest}
}

function installPackage {
  if [ "$(uname)" == "Darwin" ]; then
    sudo brew install ${1}
  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    sudo apt-get install -y ${1}
  fi
}

function checkCommand {
  if hash ${1} 2>/dev/null; then
    echo "${1} is already installed"
  else
    echo "I require ${1} but it's not installed. Installing ${1}..."
    installPackage ${1}
    echo "${1} is installed"
  fi
}

function checkShell {
  case $SHELL in
    */zsh) 
     # assume Zsh
     echo "Zsh is default shell"
     ;;
    */bash)
     # assume Bash
     echo "Bash is default shell, switching to ZSH"
     sudo chsh -s $(which zsh)
     ;;
    *)
     # assume something else
     echo "Switching default shell to ZSH"
     sudo chsh -s $(which zsh)
  esac
}

echo "[Git] > Checking if Git is installed..."
checkCommand git

echo "[Shell] > Checking if ZSH is installed..."
checkCommand zsh
checkShell
echo -e

echo "[Packages] > Checking Dependencies..."
checkCommand tmux
checkCommand tig
checkCommand nvim
echo -e

echo "[Packages] > Checking neovim dependencies..."
checkCommand python3
checkCommand python2
checkCommand ruby
checkCommand ag
echo -e

echo "[Config] > Checking config symlinks..."
linkDotfile .gitconfig
linkDotfile .config/nvim
linkDotfile .tmux.conf
linkDotfile .zshrc
linkDotfile .tigrc
echo -e

echo "[Neovim] > Checking vim installation..."
echo "[Neovim] > Installing/updating vim-plug"
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
echo "[Neovim] > Initializing vim"
nvim +PluginInstall +qall
echo "[Neovim] > Plugins Installed"
echo -e

echo "Dotfiles setup complete"
